/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Item;
import transactions.*;

public class AllItemsWindow extends javax.swing.JFrame {

    private final DefaultTableModel tableModel;
    private ItemTransaction itemTransaction = null;
    private ShoppingCartTransaction cartTransaction = null;
    private Item selectedItem = null;

    public AllItemsWindow() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Id");
        tableModel.addColumn("Name");
        tableModel.addColumn("Price");
        tableModel.addColumn("Stock Quantity");
        tableModel.addColumn("Description");

        initComponents();
        
        this.setLocationRelativeTo(null);

        itemTransaction = new ItemTransaction();

        tableModel.setRowCount(0);
        List<Item> items = itemTransaction.getAllItems();
        for (Item item : items) {
            this.tableModel.insertRow(
                    tableModel.getRowCount(),
                    new Object[]{
                        item.getId(),
                        item.getName(),
                        item.getPrice(),
                        item.getStockQuantity(),
                        item.getDescription()
                    }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        allItemsTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ALL ITEMS");

        allItemsTable.setModel(tableModel);
        allItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allItemsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allItemsTable);

        addBtn.setText("Add to Shopping Cart");
        addBtn.setEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back to main window");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(29, 29, 29)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(backBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allItemsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allItemsTableMouseClicked

        int r = allItemsTable.getSelectedRow();

        int id = Integer.parseInt(tableModel.getValueAt(r, 0).toString());
        String name = tableModel.getValueAt(r, 1).toString();
        double price = Double.parseDouble(tableModel.getValueAt(r, 2).toString());
        int stockQuantity = Integer.parseInt(tableModel.getValueAt(r, 3).toString());
        String description = tableModel.getValueAt(r, 4).toString();

        selectedItem = new Item(id, name, price, description, stockQuantity);

        if (r >= 0)
            addBtn.setEnabled(true);
    }//GEN-LAST:event_allItemsTableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        cartTransaction = new ShoppingCartTransaction();
        cartTransaction.insertItemToShoppingCart(CurrentUser.ActiveUser.getId(), selectedItem.getId());
    }//GEN-LAST:event_addBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainWindow mainWindow = new MainWindow();   
        mainWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable allItemsTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
